fix: indent

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -56,41 +56,40 @@ jobs:
           fi
 
   tests-lambda-status-video-processing:
-        name: test
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v3
+    runs-on: ubuntu-latest
+    steps:
+        - uses: actions/checkout@v3
 
-            - name: Cache Node.js modules
-              uses: actions/cache@v3
-              with:
-                    path: ~/.npm
-                    key: ${{ runner.os }}-node-22.x-${{ hashFiles('**/package-lock.json') }}
-                    restore-keys: |
-                      ${{ runner.os }}-node-22.x-
+        - name: Cache Node.js modules
+          uses: actions/cache@v3
+          with:
+                path: ~/.npm
+                key: ${{ runner.os }}-node-22.x-${{ hashFiles('**/package-lock.json') }}
+                restore-keys: |
+                  ${{ runner.os }}-node-22.x-
 
-            - name: Use Node.js 22.x
-              uses: actions/setup-node@v3
-              with:
-                  node-version: 22.x
+        - name: Use Node.js 22.x
+          uses: actions/setup-node@v3
+          with:
+              node-version: 22.x
 
-            - name: Install dependencies
-              working-directory: ./src/lambda-status-video-processing
-              run: npm ci --save-dev
+        - name: Install dependencies
+          working-directory: ./src/lambda-status-video-processing
+          run: npm ci --save-dev
 
-            - name: Unit tests
-              working-directory: ./src/lambda-status-video-processing
-              run: npm run test
+        - name: Unit tests
+          working-directory: ./src/lambda-status-video-processing
+          run: npm run test
 
-            - name: Check Jest coverage threshold
-              working-directory: ./src/lambda-status-video-processing
-              run: |
-                COVERAGE=$(cat ./coverage/lcov-report/index.html | grep -oP 'All files.*?(\d+\.\d+)%' | sed 's/[^0-9.]//g')
-                echo "Coverage: $COVERAGE"
-                if (( $(echo "$COVERAGE < 80" | bc -l) )); then
-                  echo "Coverage is below 80%! Fail the build.";
-                  exit 1;
-                fi
+        - name: Check Jest coverage threshold
+          working-directory: ./src/lambda-status-video-processing
+          run: |
+            COVERAGE=$(cat ./coverage/lcov-report/index.html | grep -oP 'All files.*?(\d+\.\d+)%' | sed 's/[^0-9.]//g')
+            echo "Coverage: $COVERAGE"
+            if (( $(echo "$COVERAGE < 80" | bc -l) )); then
+              echo "Coverage is below 80%! Fail the build.";
+              exit 1;
+            fi
 
   test-infra:
     runs-on: ubuntu-latest
